name: randomTP
version: '1.0'
main: org.amerlan.randomTP.RandomTP
api-version: '1.20'
commands:
  wild:
    description: Teleports you to a random location.
    permission: rtp.wild
permissions:
  rtp.wild:
    description: Allows users to use the /wild command.
  rtp.nocooldown:
    description: Bypasses cooldown for /wild.